// <auto-generated />
using System;
using DiaryApp.Controllers.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiaryApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250202133337_AddSeedingData")]
    partial class AddSeedingData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiaryApp.Models.DiaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiaryEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "With Alex",
                            Created = new DateTime(2024, 2, 1, 10, 30, 0, 0, DateTimeKind.Utc),
                            Title = "Went Swimming"
                        },
                        new
                        {
                            Id = 2,
                            Content = "With Maria",
                            Created = new DateTime(2024, 2, 1, 10, 30, 0, 0, DateTimeKind.Utc),
                            Title = "Went Walking"
                        },
                        new
                        {
                            Id = 3,
                            Content = "With Sofia",
                            Created = new DateTime(2024, 2, 1, 10, 30, 0, 0, DateTimeKind.Utc),
                            Title = "Went Shopping"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
